### ISSUE TITLE
前端开发入门最佳指南

### ISSUE THREAD

**Issue by zhyd1997** [zhyd1997/zhyd1997.github.io#1]
缘起 [The Best Way to Learn Frontend Web Development](https://www.freecodecamp.org/news/learn-frontend-web-development/)，多读几遍体会一下

# HTML(5)

# CSS(3)
基础只需看完 Part 1 - 2，满满的面试考点。
<div style="display:flex">
    <img src="https://images.manning.com/360/480/resize/book/1/05a18b1-751e-4bcd-9d61-71757f0d2d54/Grant-CSS-HI.png" width="250" height="328" alt="CSS in Depth" />
</div>

📚[CSS in Depth](https://learning.oreilly.com/library/view/css-in-depth/9781617293450/)

# JavaScript (ES6+)

**蝴蝶书**、**红宝书** 、**犀牛书**，这三本书当作工具书
<div style="display:flex">
    <img src="https://www.safaribooksonline.com/library/cover/9780596517748/250w/" width="250" height="328" alt="JavaScript: The Good Parts">
    <img src="https://media.wiley.com/product_data/coverImage300/45/11193664/1119366445.jpg" width="250" height="328" alt="Professional JavaScript for Web Developers, 4th Edition">
    <img src="https://www.safaribooksonline.com/library/cover/9781491952016/250w/" width="250" height="328" alt="JavaScript: The Definitive Guide, 7th Edition">
    <img src="https://eloquentjavascript.net/img/cover.jpg" width="250" height="328" alt="Eloquent JavaScript">
    </div>

觉得还是 [javascript.info](https://javascript.info/) 更好，难点有更直观的图解

📚[Eloquent JavaScript](https://eloquentjavascript.net/) 这本书分三部分，附带质量很高的 Project，纸质版也只有 478 页
> 最新在线正版书籍链接

英文版：

📚[JavaScript: The Good Parts](https://www.oreilly.com/library/view/javascript-the-good/9780596517748/)

📚[JavaScript: The Definitive Guide, 7th Edition](https://www.oreilly.com/library/view/javascript-the-definitive/9781491952016/)

📚[Professional JavaScript for Web Developers, 4th Edition](https://www.oreilly.com/library/view/professional-javascript-for/9781119366447/)

中文版：

📚[JavaScript语言精粹](https://book.douban.com/subject/11874748/)

📚[JavaScript编程精解(第3版)](https://book.douban.com/subject/35011711/)

> MDN 当作工具书或者运行小段代码挺好用，和 console 同步（ console 直接写代码会有变量冲突等等问题

**Comment by 007tom** [comment]
英文版：
📚[Professional JavaScript for Web Developers, 4th Edition](https://www.oreilly.com/library/view/professional-javascript-for/9781119366447/)

**Comment by 007tom** [comment]
JS module system: --> [twitter](https://twitter.com/fullstackio/status/1425106064941404167?s=20)

<img width="600" alt="Screen Shot 2021-08-11 at 09 11 45" src="https://user-images.githubusercontent.com/31362988/128954680-e043c931-234d-4344-81b2-d5803927e2d2.png">

For more details, see the thread on Twitter above.
